language: node_js


node_js:
  - '12'

env: 
DATABASE_URL || 'postgresql://codex:pg123@localhost:5432/test';

before_script:
  - psql -c 'create database  test;' -U postgres
  - psql -U postgres -d test -a -f tables.sql

services:
  - postgresql